Remove broken notebook deploy.ipynb.
Relies on a call to `t5_mesh_transformer`, which uses an outdated pip package that is no longer maintained and contains broken references, e.g.:

```
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function'
```
PiperOrigin-RevId: 576658895